image: Visual Studio 2019

build:
  verbosity: detailed

cache:
  - '%APPDATA%\npm-cache -> package-lock.json'
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

install:
  - ps: Install-Product node 12 x64
  - dotnet tool restore

build_script:
  - cmd: dotnet fake build -t Dist
